# ****************************************************************************************************************
# Spatial description of the environment

generation_folder: '/home/fernand0labra/rai-subtgraph/data/'
generation_n_worlds: 10

generation_seed: 11

connection_avg_width: 300

world_max_length: 500               # In meters
world_topology: 'natural'          # operational, natural, lavatube
world_mission_navigation: 'mixed'   # ground, uav, mixed

world_n_levels: 5
world_n_loops_per_level: 2
world_n_tjunctions_per_level: 0
world_n_intersections_per_level: 1


# ****************************************************************************************************************
# Repository paths

# minibla
asset_path: '/home/fernand0labra/rai-subtgraph/assets/subt/'

# minibla
darpa_dimensions_type_a: '/home/fernand0labra/rai-subtgraph/config/dimensions-type-a.yaml'
darpa_dimensions_type_b: '/home/fernand0labra/rai-subtgraph/config/dimensions-type-b.yaml'


# ****************************************************************************************************************
# Textures

cave_wall: 'CaveWall_Natural.png'
rock_pile: 'RockPile_Natural.jpg'
striated_rock: 'StriatedRock_Natural.jpg'


# ****************************************************************************************************************
# Node names and descriptions

env_asset_list_type_a:
  node: 
    parameters: 'node'
    assets: [
      "cave_corner_01_type_a",
      "cave_corner_03_type_a",
    ]

  corner:       
    parameters: 'corner,e,s'
    assets: [
      "cave_corner_01_type_b",
      "cave_corner_02_type_b",
    ]

  straight:     
    parameters: 'straight,e,w'
    assets: [
      "cave_cavern_type_a",
      "cave_split_type_a",
    ]

  junction:     
    parameters: 'junction,e,n,s'
    assets: [
      "cave_3_way_01_type_b"
    ]

  intersection: 
    parameters: 'intersection,e,n,s,w'
    assets: [
      "cave_4_way_01_type_a",
    ]

env_asset_list_type_b:  # minibla  TODO
  node: 
    parameters: 'node'
    assets: [
      "cave_corner_01_type_b",
      "cave_corner_02_type_b",
    ]

  corner:       
    parameters: 'corner,e,s'
    assets: [
      "cave_corner_01_type_b",
      "cave_corner_02_type_b",
    ]

  straight:     
    parameters: 'straight,e,w'
    assets: [
      "cave_straight_01_type_b",
      "cave_straight_02_type_b",
      "cave_straight_03_type_b",
      "cave_straight_04_type_b",
      "cave_straight_05_type_b",
    ]

  shaft: 
    parameters: 'shaft,e,n,s,w'
    assets: [
      # "cave_vertical_shaft_type_b",
      "cave_elevation_type_b"
    ]

  junction:     
    parameters: 'junction,e,n,s'
    assets: [
      "cave_3_way_01_type_b"
    ]

  intersection: 
    parameters: 'intersection,e,n,s,w'
    assets: [
      "cave_4_way_01_type_b",
    ]