folder: "type_a"

cave_3_way_type_a:
  pos: [130.0, 130.0, 0]
  name: "3way"

cave_4_way_01_type_a:
  pos: [130.0, 130.0, 0]
  name: "4way01"

cave_cap_type_a:
  pos: [0.0, 0.0, 0.0]
  name: "cap"

cave_cavern_type_a:
  pos: [130.0, 130.0, 0.0]
  name: "cavern"

cave_corner_01_type_a:
  pos: [130.0, 130.0, 0.0]
  name: "corner01"

cave_corner_03_type_a:
  pos: [130.0, 130.0, 0.0]
  name: "corner03"

cave_elevation_02_type_a:
  pos: [250.0, 250.0, 375.0]
  name: "elevation02"

cave_elevation_straight_type_a:
  pos: [250.0, 250.0, 130.0]
  name: "elevationstraight01"

cave_split_type_a:
  pos: [130.0, 130.0, 0.0]
  name: "split"

cave_straight_type_a:
  pos: [130.0, 130.0, 0.0]
  name: "straight"
