folder: "type_b"

cave_3_way_01_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cave3way"

cave_4_way_01_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cave4way"

cave_cap_type_b:
  pos: [0.0, 0.0, 0.0]
  name: "cavecap"

cave_corner_01_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavecorner01"

cave_corner_02_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavecorner02"

cave_elevation_type_b:
  pos: [40.0, 40.0, 32.0]
  name: "caveelevation"

cave_straight_01_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavestraight01"

cave_straight_02_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavestraight02"

cave_straight_03_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavestraight03"

cave_straight_04_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavestraight04"

cave_straight_05_type_b:
  pos: [40.0, 40.0, 0.0]
  name: "cavestraight05"

cave_vertical_shaft_type_b:
  pos: [40.0, 40.0, 64.0]
  name: "caveverticalshaft"
